### ISSUE TITLE
[BUG] Using Win + E creates screenshot before opening a new tab

### ISSUE THREAD

**Issue by enoversum** [w4po/ExplorerTabUtility#53]
### Has this bug been raised before?

- [x] I have checked "open" AND "closed" issues and this is not a duplicate

### Describe your issue:

I suppose it's some compatibility thingy with Windows' Sniping tool, but as soon as I run ExplorerTabUtility, hitting Win + E to open a new tab creates a screenshot (screen is darkened for half a second) before opening the new tab. As soon as I disable the shortcut inside ETU, when no Explorer window is visibly open, no screenshot is being created. As soon as there is an open Explorer window, Win + E does nothing else but create a screenshot. If I unload ETU, Win + E behaves normally and just opens a new Explorer window.

I haven't bound this shortcut to do this, I have no idea where this comes from. Since it's only happening when ETU is running, I suspect it might have something to do with it :) . 

### What OS do you have?

Windows 11

### What edition?

Pro

### OS Version?

24H2

### OS Build?

26120.3576

### Have you tweaked your Windows 11 look?

Yes

### If "Yes" to the above, please explain how or what tools you have used.

ExplorerBlurMica, DWMBlur

**Comment by w4po** [comment]
Thanks for reporting this!
This issue should be fixed in the upcoming release.
Let me know if you run into any other problems, and I really appreciate your feedback! ♥️

**Comment by Rosaldivo** [comment]
This bug is still happening on my Windows 11 24H2, using v2.6.
